on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: .\Tools\nircmd.exe savescreenshot screenshot.png
    - uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
        overwrite: true
